### PR TITLE
Project updates

### PR DESCRIPTION
**Pull request by friederbluemle**
Various project updates. Best reviewed commit by commit.
Let me know if you want me to split it up into multiple PRs. Thanks.

### CODE REVIEW

**Comment by StevenDiviney** [comment]
@friederbluemle thanks for the contribution. We can't merge this with a failing build. I [opened a test PR](https://github.com/zendesk/sdk_demo_app_android/pull/54) to see if there is a problem with our CI currently and [there doesn't seem to be](https://travis-ci.org/zendesk/sdk_demo_app_android/builds/200350885).

I talked to some Androids and they suggested it might be to do with updating the gradle wrapper, or wrapping the release config in an if.

**Comment by friederbluemle** [comment]
@StevenDiviney Thanks for the comment. I'll look into it!

**Comment by friederbluemle** [comment]
@StevenDiviney After some tests, it turned out that the Travis failure is unrelated to any changes I made in this PR.

The exact error on Travis is this:

    $ openssl aes-256-cbc -K $encrypted_218b70c0d15d_key -iv $encrypted_218b70c0d15d_iv -in scripts/rtd.jks.enc -out scripts/rtd.jks -d
    iv undefined

That means the variable `$encrypted_218b70c0d15d_iv` is empty (undefined). Do you happen to know where it is supposed to get its value from?

**Comment by brendan-fahy** [comment]
Hey @friederbluemle,

I've tried adding your commits one-by-one in another PR (https://github.com/zendesk/sdk_demo_app_android/pull/55) to see which one breaks the Travis build (except for the whitespace commit), and none of them did. So I don't know why it's failing on your PR. It seems to build fine on all the constituent parts.

Would you like to try breaking this PR into several smaller PRs, and see if CI passes on each of them? If we find something bad, we can look into it then, and in the meantime we can get the other commits merged. 

Thanks,

Brendan

**Comment by friederbluemle** [comment]
Hey @brendan-fahy 
Thanks a lot for testing! I also tried pushing only a subset of the commits to my branch, but like you said, non of the commits break the build. As you can see from the Travis logs (and as I mentioned in the previous commit), the build failure is due to an undefined environment variable on Travis. The only reason I can think of why this happening is due a difference in the Travis accounts. My PR (of course) comes from my fork, the test PR you opened comes from the same repo. Can you try opening the PR from your fork (not just a new branch in the main repo)?

**Comment by friederbluemle** [comment]
I created #56 to test Travis CI

**Comment by baz8080** [comment]
@friederbluemle I'm going to be making the project work properly with forks.

**Comment by friederbluemle** [comment]
@baz8080 see #57 for my attempt (now updated)

**Comment by friederbluemle** [comment]
Commits rebased and (partially) squashed. After #58 got merged, #55, #56, and #57 are no longer needed, and this PR build should now succeed. Please let me know if anything else is needed.

**Comment by baz8080** [comment]
Thanks @friederbluemle 

We'll merge on green. I can't guarantee that we will be as ruthless with the whitespace as you though ;)

**Comment by friederbluemle** [comment]
Thanks @baz8080 :+1:

**Pull request merged**
